trigger: 
- main

resources:
  repositories:
    - repository: configRepo
      type: github
      ref: main
      endpoint: mvankrieken
      name: mvankrieken/argocd-config

pool: 
  name: Local-kubernetes
  demands: 
    - DEF_TYPE -equals build

workspace:
  clean: all 

steps:
 # Checkouts
 - checkout: self
   path: '$(System.DefaultWorkingDirectory)/workspace'
 - checkout: configRepo
   path: '$(System.DefaultWorkingDirectory)/configRepo'

 - bash: "pwd"
   name: "CurrentDir"
 - bash: "ls -al"
   name: "ListDir"
 - bash: "echo  '$(System.DefaultWorkingDirectory)'" 
   name: "Workdir"  
 - bash: 
    echo "##vso[task.setvariable variable=GIT_SHORT_ID]$(echo $(Build.SourceVersion) | cut -c1-7)"
 - task: Docker@2
   displayName: Build agent image
   inputs:
     repository: 'local/az-local-agent'
     command: build
     Dockerfile: /workspace/image/azure-agent.dockerfile
     buildContext: /workspace/work/image
     tags: $(GIT_SHORT_ID)
     arguments: '--platform linux/x86_64'