trigger: 
- main

resources:
  repositories:
    - repository: configRepo
      type: github
      ref: main
      endpoint: mvankrieken
      name: mvankrieken/argocd-config

pool: 
  name: Local-kubernetes
  demands: 
    - DEF_TYPE -equals build

workspace:
  clean: all 

steps:
 - bash: 
    echo "##vso[task.setvariable variable=GIT_SHORT_ID]$(echo $(Build.SourceVersion) | cut -c1-7)"
    
 - task: Docker@2
   displayName: Build agent image
   inputs:
     repository: 'local/az-local-agent'
     command: build
     Dockerfile: image/azure-agent.dockerfile
     buildContext: image
     tags: $(GIT_SHORT_ID)
     arguments: '--platform linux/x86_64'

 - checkout: configRepo
   path: configRepo
       