trigger: 
- main

pool: 
  name: Local-kubernetes
  demands: 
    - DEF_TYPE -equals build


steps:
 - bash: |
    export GIT_SHORT_ID=$(echo $(Build.SourceVersion) | cut -c1-7 ) 

 - task: Docker@2
   displayName: Build agent image
   inputs:
     repository: 'local/az-local-agent'
     command: build
     Dockerfile: image/azure-agent.dockerfile
     buildContext: image
     tags: $[GIT_SHORT_ID]
     arguments: '--platform linux/x86_64'