trigger: 
- main

pool: 
  name: Local-kubernetes
  demands: 
    - DEF_TYPE -equals build

steps:
 - bash: |
    ls -l /var/run/docker.sock

 - task: Docker@2
   displayName: Build agent image
   inputs:
     repository: 'local/az-local-agent'
     command: build
     Dockerfile: image/azure-agent.dockerfile
     buildContext: image
     tags: $(Build.BuildId)