trigger: 
- main

pool: 
  name: Local-kubernetes
  demands: 
    - DEF_TYPE -equals build

variables:
  GitHash: ${BUILD_SOURCEVERSION:0:8}

steps:

 - task: Docker@2
   displayName: Build agent image
   inputs:
     repository: 'local/az-local-agent'
     command: build
     Dockerfile: image/azure-agent.dockerfile
     buildContext: image
     tags: $(GitHash)
     arguments: '--platform linux/x86_64'