trigger: 
- main

resources:
  repositories:
    - repository: configRepo
      type: github
      ref: main
      endpoint: mvankrieken
      name: mvankrieken/argocd-config

pool: 
  name: Local-kubernetes
  demands: 
    - DEF_TYPE -equals build

workspace:
  clean: all 

steps:
 # Checkouts main code
 - checkout: self

 # Build image
 - bash: 
    echo "##vso[task.setvariable variable=GIT_SHORT_ID]$(echo $(Build.SourceVersion) | cut -c1-7)"

 # Checkout config
 - checkout: configRepo

 # Update deployment file
 #- bash: yq -i '.spec.template.spec.containers[].image = "local/az-local-agent:$(GIT_SHORT_ID)"' deployment.yaml
 - bash: yq --help