trigger: 
- main

resources:
  repositories:
    - repository: configRepo
      type: github
      ref: main
      endpoint: mvankrieken
      name: mvankrieken/argocd-config

pool: 
  name: Local-kubernetes
  demands: 
    - DEF_TYPE -equals build

workspace:
  clean: all 

steps:
 # Checkouts main code
 - checkout: self

 # Build image
 - bash: 
    echo "##vso[task.setvariable variable=GIT_SHORT_ID]$(echo $(Build.SourceVersion) | cut -c1-7)"

 # Checkout config
 - checkout: configRepo
   clean: true
   persistCredentials: true
   sparseCheckoutDirectories: azure-build-agent

 # Update deployment file
 - script: |
    cd argocd-config/
    git config --global user.email "mkrieken@gmail.com"
    git config --global user.name "Martin van Krieken"
    git fetch
    git branch -v -a
    git switch remotes/origin/main
    yq eval -i '.spec.template.spec.containers[].image = "local/az-local-agent:$(GIT_SHORT_ID)"' azure-build-agent/deployment.yaml
    git add .
    git commit -m "New version for azure-build-agent/deployment.yaml"
    git push origin remotes/origin/main